### PR TITLE
Update to newest GTFS library

### PR DESCRIPTION
**Pull request by bnitkin**

### CODE REVIEW

**Comment by ZanettaPM** [comment]
I used your new branch and it is working great for my GTFS data in France. 
Unfortunately, it shows three times the same departure time for each route and gives also negative departure times... 
I will try to dig in your code and see if I can change this but if you have any ideas 
Thanks for your work that's awesome,
Best, 
image

**Comment by ZanettaPM** [comment]
Also that would be dope to have the time < 5 min as "from now" (i.e. in minutes) and the other ones as digital hours !

**Comment by bnitkin** [comment]
Thanks! Appreciate the feedback :)

I like the thought of switching from wall clock hours-minutes to minutes-to-departure, working on adding that as an option now.

I've also fixed the negative time issue. I don't remove trips from the list until a few minutes after the scheduled time in case it's running late. But those trips can be removed after checking for realtime data.

There are a few possible causes for duplicate times. Do you have logs from the browser? Off the top of my head, the `station` filter may be too broad & capturing adjacent stops, or my filtering logic might fail on France's data.

If you're using a Pi, you can add something like this to `broadcast()` as trips are added to `results`.

```
Log.log(route.route_long_name + " towards " + trip.trip_headsign + " at " + datetime + " #" + trip.trip_id);
```

**Comment by bnitkin** [comment]
My PC was acting up yesterday but I tested the changes this morning before pushing.

`showTimeFromNow` is now minutes as an integer instead of a boolean - if you make it `5`, trips will show clock times until 5 minutes to departure, then swap over.

And trips are now pruned after checking realtime data so departed buses won't show up. (I still see some -0's... not sure why JS renders negative zero and positive zero differently.)

There's a commented-out log message for verbosely printing trips in the new commits too. That'll narrow down the duplicate times in your module.

**Comment by ZanettaPM** [comment]
Good evening, 

Sorry, I've been meaning to get back to you for a few weeks but I've been swamped with work. 

I've made a lot of changes to your new version of your code to try and figure out what was wrong with it. 

My data is in GTFS, I don't have RealTime data, so this was already a problem. I removed most of the functions that readjusted RealTime to work on simpler code, but that didn't solve the problem. 

Overall, using the logs, I realized that the problem came from the service_id in the calendar textfile. I don't know why, but there are service overlays. I'm going to contact the city's service department to try and decipher the meaning of these service_ids to understand which are the data for normal periods, vacation periods etc. 

If you want, I'll put you the link to the data, until I get some feedback from the city department. It is the link from the gouvernemental website (https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-stas). 

https://api.saint-etienne-metropole.fr/stas/api/horraires_tc/GTFS.aspx

Thank you very much for your help and for this great project you're offering to the community. 

Best,

**Comment by bnitkin** [comment]
Thanks for the link! And don't worry about timing - I'm glad to help with issues, but we all have other priorities in life.

The duplicate trips are coming from somewhere in `node_helper.js` - either there's an issue there or the source data contains multiple copies of each trip for some reason.

Using this config:
```
        {
            module: "MMM-transitfeed",
            position: "center",
            config: {
                gtfs_config: {
                    agencies: [
                        {
                            "url": "https://api.saint-etienne-metropole.fr/stas/api/horraires_tc/GTFS.aspx",
                            // Excluding shapes makes loading faster.
                            exclude: ['shapes']
                        },
                    ],
                },

                // Route + station pairs to monitor for departures
                queries: [
                    {route_name: "2", stop_name: "RUE EMILE"},
                ],
            },
        },
```

I see this in the developer console (F12 -> Console on Firefox). You can see three copies of each trip - same `stop_time`, `route_id`, and `direction` but different `trip_id`s.
image

**Comment by bnitkin** [comment]
That looks like the trouble - each entry shows up three times. If you add more `departuresPerRoute`, then there's three of each one.

As an aside, all the GTFS logic turns off automatically if `agencies.realtime` is empty. You can provide just the `agencies.urls` scheduled GTFS URL.  

image

I bet this is the cause:
```
210    // Start/end dates are ignored for calendars, as are holidays.
```
My calendar parsing logic generates trips based on day-of-week schedule, but doesn't check start/end dates for the calendar. So if your agency is posting summer and winter schedules, my logic will generate a trip for both.

Taking a look at the trips in that last screenshot:
```
trip_id: 2961
    trips.txt -> 02,V3-5-1-127,2961,GARE FIRMINY,1,,,
    calendar.txt -> V3-5-1-127,1,1,1,1,1,1,1,20240224,20240224
    -> Special trip for 2024-02-24
trip_id: 2432
    trips.txt -> 02,H3-5-1-127,2432,GARE FIRMINY,1,,,
    calendar.txt -> H3-5-1-127,1,1,1,1,1,1,1,20240217,20240217
    -> Special trip for 2024-02-17
trip_id: 2149
    trips.txt -> 02,H1-5-1-127,2149,GARE FIRMINY,1,,,
    calendar.txt -> H1-5-1-127,1,1,1,1,1,1,1,20240210,20240413
    -> Normal trip for 2024-02-10 through 2024-04-13
```

So only the third trip, `2149`, should actually display. The fix is to check the candidate date against the `start_date` and `end_date` in `calendar.txt`. If you'd like to take a shot at it and put in a PR, feel free! Otherwise I'll take a closer look when I have downtime.

_i think that trip #2149 is still valid for 2-17 and 2-24, which would leave duplicates on those specific days and is a little weird. do you know what to make of that?_

**Comment by bnitkin** [comment]
Last thought - it looks like your dataset updates much more often than I'm used to as a Philadelphia person. I bet they adjust the calendars to make remove holidays from the normal service calendar, but only on the week of the holiday.

As written, this module only downloads data on startup. You might want to update periodically on a very slow timer (once a day or week or whatever). Again, feel free to submit a PR!

**Comment by ZanettaPM** [comment]
Hey bnitkin, after a long time (I've been working on this on the side ahah) I finally managed to beat the beast. It took me a long time because I trusted the dataset so much. However, this was a mistake because their datasets return duplicates for the same query. I first added a small function to remove service_ids that should not apply to a given day, but even with this I had departure times from sunday showing up on saturday. After checking their calendar.txt I mentioned that their weekend trips were somehow corrupted and showing a value of "1" for all days of the week. Anyway, long story short, I had to reverse engineer their service_ids by comparing the GTFS data to the schedule displayed at the stops in various place of the city. I contacted the guy that is in charge of providing the data only (it is a mandatory in France) but he never replied... I think he only deal with big apps developpers... that's a shame. 
 
I decided to play a bit with the code since it was just for me and I did not plan to submit it to github. One small functionality I added is to grab the color of the line (in gtfs.getRoutes) to change the terminus.style.color. It exists in some GTFS data. It might be something you want to add in the future ;)  (do not forget to modify the replace text function to keep those colors)

As for updating the dataset (thank you very much for your advice and for trying to foresee any difficultyites) it is actually not a problem for me because my magic mirror is set to stop every night (after midnight) and restart early in the morning to reduce energy consomation. 

Thanks again for your help and for your nice module ;)

image

**Comment by bnitkin** [comment]
Glad to hear it! If you ever do want to submit pieces you've done as a PR, feel free!

I'm glad it's working well for you. GTFS data is definitely fiddlier to use than the dedicated MagicMirror modules for specific transit agencies, but I like that it works for basically any agency.

**Pull request merged**
